#!/bin/bash


SOURCE_DIR="$(cd "$(dirname "$0")" && pwd)"
source ${SOURCE_DIR}/script/print_functions.sh


echo ""
info "If you have a private directory, copy it in your dotfiles directory"
info "and setup your ssh credentials before continue"
info ""
user "Do you wish to do the install now ?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) break;;
        No ) exit;;
    esac
done


echo ""
user "What kind of install ?"
info "  Simple: only dotfiles and plugin manager"
info "  Server: simple install + private install scripts"
info "  Desktop: full Ubuntu install"
select i in "Simple" "Server" "Desktop" "Quit"; do
    case $i in
        Simple )
            ${SOURCE_DIR}/script/install_simple
            break
            ;;
        Server )
            ${SOURCE_DIR}/script/install_server
            break
            ;;
        Desktop )
            ${SOURCE_DIR}/script/install_desktop
            break
            ;;
        Quit ) exit;;
    esac
done

