#!/bin/bash


SOURCE_DIR="$(cd "$(dirname "$0")" && pwd)"
source ${SOURCE_DIR}/print_functions.sh
RELEASE="$(lsb_release -sc)"


echo ""
info "Make usefull directories & links"
for path in local Projets Sandbox
do
    mkdir -p ${HOME}/${path}
done
#mkdir ${HOME}/local
#mkdir ${HOME}/Projets
#mkdir ${HOME}/Sandbox
ln -s ${HOME}/dotfiles/bin ${HOME}
ln -s ${HOME}/dotfiles/modulefiles ${HOME}/local
if [ -d ${HOME}/dotfiles/private/ssh ]
then
    chmod -R 700 ${HOME}/dotfiles/private/ssh
    chmod 600 ${HOME}/dotfiles/private/ssh/*
    mkdir -p ${HOME}/.ssh
    cp ${HOME}/dotfiles/private/ssh/id_rs* ${HOME}/.ssh
fi


echo ""
info "Add repositories"

# This step won't be needed after Ubuntu 16.04
info "Arc"
wget "http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_16.04/Release.key"
sudo apt-key add - < Release.key
rm Release.key
sudo apt-add-repository -y 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/ /'

info "DropBox"
sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
sudo apt-add-repository -y 'deb http://linux.dropbox.com/ubuntu xenial main'

info "Moka"
sudo apt-add-repository -y ppa:moka/daily

info "Neovim"
sudo apt-add-repository -y ppa:neovim-ppa/stable

# No need for Ubuntu 16.04
#info "Solaar"
#sudo apt-add-repository -y ppa:daniel.pavel/solaar

info "Spotify"
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886
sudo apt-add-repository -y 'deb http://repository.spotify.com stable non-free'

info "Steam: Multiverse"
sudo apt-add-repository -y multiverse


echo ""
info "Make sure everything is up to date before messing with stuff"
sudo apt update
sudo apt upgrade -y


echo ""
info "Install a bunch of stuff"
sudo apt install -y \
    build-essential \
    cmake \
    colordiff \
    curl \
    gimp \
    git \
    gnucash libdbd-sqlite3\
    gramps \
    htop \
    keepassx \
    libreoffice \
    lmod \
    pandoc \
    solaar \
    texlive \
    tmux \
    vlc \
    xdotool
#clementine hexchat inkscape powertop sparkleshare xdotool
sudo apt install -y arc-theme
sudo apt install -y dropbox
sudo apt install -y moka-icon-theme
sudo apt install -y neovim
sudo apt install -y spotify-client
sudo apt install -y steam
#Slack
sudo apt install -y ${HOME}"/dotfiles/private/src/slack-desktop-2.4.2-amd64.deb"
#Freesurfer
sudo apt install -y tcsh
sudo apt upgrade -y
sudo apt autoremove -y


echo ""
info "Install Rust"
s="install_rust"
curl https://sh.rustup.rs -sSf > ${s}
chmod u+x ${s}
./${s} --no-modify-path -y
rm ${s}


${SOURCE_DIR}/install_simple


echo ""
info "Build vim-markdown-composer"
orig=$(pwd)
cd ${HOME}/.vim/bundle/vim-markdown-composer/
${HOME}/.cargo/bin/cargo build --release
cd ${orig}


echo ""
info "Install online repos for desktop"
${SOURCE_DIR}/install_repos_desktop


echo ""
cmd=${HOME}"/dotfiles/private/install_git_repos"
if [[ -f "${cmd}" ]]
then
    info "Install git repos"
    chmod u+x ${cmd}
    ${cmd}
fi


echo ""
info "Setup gsettings"
${SOURCE_DIR}/setup_gsettings


echo ""
cmd=${HOME}"/dotfiles/private/install_src"
if [[ -f "${cmd}" ]]
then
    info "Install sofwares from private/src"
    chmod u+x ${cmd}
    ${cmd}
fi

sudo apt install -y gnome-tweak-tool

echo ""
success " All install done !!"
echo ""
user "Things to do:"
#info "YouCompleteMe not compile"
#info "launch 'script/compile_YouCompleteMe' after loading anaconda"
info "1. DropBox"
info "2. Tmux plugin manager: prefix + I in a tmux session"
info "3. Arc for Firefox"
info "    https://github.com/horst3180/arc-firefox-theme"
info "    https://addons.mozilla.org/en/firefox/collections/horst3180/a/"
info "4. Firefox Sync"
info "5. In about:config set browser.backspace_action to 0"
info "6. Liberation Mono (14) for each profile"
info "7. Add French and let Ubuntu install packages"
info ""
info "RESTART !o!"

