#!/bin/bash


SOURCE_DIR="$(cd "$(dirname "$0")" && pwd)"
source ${SOURCE_DIR}/print_functions.sh
#RELEASE="$(lsb_release -sc)"


echo ""
info "Make usefull directories & links"
mkdir ${HOME}/local
mkdir ${HOME}/Projets
mkdir ${HOME}/Sandbox
ln -s ${HOME}/dotfiles/bin ${HOME}
#ln -s ${HOME}/dotfiles/modulefiles ${HOME}/local
chmod -R 700 ${HOME}/dotfiles/private/ssh
chmod 600 ${HOME}/dotfiles/private/ssh/*


${SOURCE_DIR}/install_simple


echo ""
cmd=${HOME}"/dotfiles/private/install_git_repos"
if [[ -f "${cmd}" ]]
then
    info "Install git repos"
    chmod u+x ${cmd}
    ${cmd}
fi


echo ""
cmd=${HOME}"/dotfiles/private/install_src"
if [[ -f "${cmd}" ]]
then
    info "Install sofwares from private/src"
    chmod u+x ${cmd}
    ${cmd}
fi


echo ""
success " All install done !!"
echo ""
user "Things to do:"
#info "YouCompleteMe not compile"
#info "launch 'script/compile_YouCompleteMe' after loading anaconda"
info "1. Tmux plugin manager: prefix + I in a tmux session"

