#!/bin/bash


SOURCE_DIR="$(cd "$(dirname "$0")" && pwd)"
source ${SOURCE_DIR}/print_functions.sh
RELEASE="$(lsb_release -sc)"


echo ""
info "Make usefull directories & links"
mkdir ${HOME}/local
mkdir ${HOME}/Projets
mkdir ${HOME}/Sandbox
ln -sf ${HOME}/dotfiles/modulefiles ${HOME}/.modulefiles
chmod -R 700 ${HOME}/dotfiles/private/ssh
chmod 600 ${HOME}/dotfiles/private/ssh/*


echo ""
info "Install dotfiles"
${SOURCE_DIR}/install_dotfiles


echo ""
info "Add repositories"

# This step won't be needed after Ubuntu 16.04
info "Arc"
wget "http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_16.04/Release.key"
sudo apt-key add - < Release.key
rm Release.key
sudo apt-add-repository -y 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/ /'

info "DropBox"
sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
sudo apt-add-repository -y 'deb http://linux.dropbox.com/ubuntu xenial main'

info "Moka"
sudo apt-add-repository -y ppa:moka/daily

# No need for Ubuntu 16.04
#info "Solaar"
#sudo apt-add-repository -y ppa:daniel.pavel/solaar

info "Spotify"
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886
sudo apt-add-repository -y 'deb http://repository.spotify.com stable non-free'

info "Steam: Multiverse"
sudo apt-add-repository -y multiverse


echo ""
info "Make sure everything is up to date before messing with stuff"
sudo apt update
sudo apt upgrade -y


echo ""
info "Install a bunch of stuff"
sudo apt install -y build-essential cmake colordiff curl gimp git gnome-tweak-tool gnucash htop keepassx libreoffice pandoc solaar texlive tmux vim vlc
#clementine hexchat inkscape powertop sparkleshare xdotool
sudo apt install -y arc-theme
sudo apt install -y dropbox
sudo apt install -y moka-icon-theme
sudo apt install -y spotify-client
sudo apt install -y steam
#Slack
sudo apt install -y ${HOME}"/dotfiles/private/src/slack-desktop-2.4.2-amd64.deb"
sudo apt upgrade -y


echo ""
info "Install online repos for desktop"
${SOURCE_DIR}/install_repos_desktop


echo ""
cmd=${HOME}"/dotfiles/private/install_git_repos"
if [[ -f "${cmd}" ]]
then
    info "Install git repos"
    chmod u+x ${cmd}
    ${cmd}
fi


echo ""
info "Install plugin managers"
${SOURCE_DIR}/install_plugin_manager


echo ""
info "Setup gsettings"
${SOURCE_DIR}/setup_gsettings


echo ""
info "Cleaning up"
sudo apt autoremove -y


echo ""
cmd="${SOURCE_DIR}/private/install_src"
if [[ -f "${cmd}" ]]
then
    info "Install sofwares from private/src"
    chmod u+x ${cmd}
    ${cmd}
fi


echo ""
success " All install done"
echo ""
user "Things to do:"
echo ""
info "YouCompleteMe not compile"
info "launch 'script/compile_YouCompleteMe' after loading anaconda"
echo ""
info "Tmux plugin manager: prefix + I in a tmux session"
echo ""
info "Arc for Firefox"
info "https://github.com/horst3180/arc-firefox-theme"
info "https://addons.mozilla.org/en/firefox/collections/horst3180/a/"
echo ""
info "Firefox Sync"
echo ""
info "Select 'Liberation Mono' size 14 for each profile"

