#!/bin/bash


SOURCE_DIR="$(cd "$(dirname "$0")" && pwd)"
source ${SOURCE_DIR}/print_functions.sh


echo ""
info "Install tmux plugin manager"
dst=${HOME}/.tmux/plugins
mkdir -p ${dst} && cd ${dst}
git clone https://github.com/tmux-plugins/tpm


echo ""
info "Install vim plugin manager"
dst=${HOME}/.vim/bundle
mkdir -p ${dst} && cd ${dst}
git clone https://github.com/VundleVim/Vundle.vim.git
vim +PluginInstall +qall

#${HOME}/dotfiles/script/compile_YouCompleteMe
